### 用 refresh token 換新 access token
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDkyMDE3MiwiZXhwIjoxNzUxNTI0OTcyfQ.6EY-l9DUi2N0ddjYShnQkuoxPnzNQRrMArOomjo14No"
}

### 取得所有使用者
GET http://localhost:3000/api/users

### 新增一位使用者
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Charlie"
}

### 更新使用者
PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
  "name": "Updated Bob"
}

### 刪除使用者
DELETE http://localhost:3000/api/users/1

### 註冊帳號
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "1234567890"
}

### 登入帳號
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "1234567890"
}

### 使用 Token 存取受保護 API
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

### 建立新筆記
POST http://localhost:3000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

{
  "title": "我的第一篇筆記",
  "content": "今天完成了 Node.js 登入系統！"
}

### 取得筆記清單
GET http://localhost:3000/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

### 更新筆記
PUT http://localhost:3000/api/notes/685a740945ac67e32adee55d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

{
  "title": "更新筆記標題",
  "content": "更新了筆記內容！"
}

### 刪除筆記
DELETE http://localhost:3000/api/notes/685a740945ac67e32adee55d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

### 建立任務
POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

{
  "title": "完成 App 任務模組"
}

### 取得任務清單
GET http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

### 更新任務
PUT http://localhost:3000/api/tasks/685b98b084643936f3956ddc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0

{
  "title": "更新任務標題 - 已完成",
  "done": true
}

### 刪除任務
DELETE http://localhost:3000/api/tasks/685b98b084643936f3956ddc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWE1ZjExOTdkZDVmMjRjZTUxZDEwMCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDgzMzE3NiwiZXhwIjoxNzUwODQwMzc2fQ.BO-V2UxphqK032098OvF4mqqJXW8euu_LgFf16lIzd0